sample:		sample.cpp sphere.cpp bmptotexture.cpp rick_astley.cpp
	g++ -o a3  sample.cpp \
	-lm -framework OpenGL \
	-framework GLUT \
	-Wno-deprecated-declarations \
	-Wno-c++11-compat-deprecated-writable-strings

clean:
	rm a3
