sample:		sample.cpp bezier.cpp bezier.h
	g++ -o sample  sample.cpp   -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings

clean:
	rm ./sample
